# Generated by Django 4.2 on 2024-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform_alter_flan_flan_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contacto',
        ),
    ]
