# Generated by Django 4.2 on 2024-05-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=500, max_digits=10),
        ),
    ]
